/**
 * Stage 2 Phase 3/4 - GitHub App authentication and webhook verification. This is CODE ONLY: no App is
 * registered on GitHub yet (see docs/research/2026-08-21-stage2-architecture.md for the manifest this
 * code expects and the exact steps to register one). Nothing in this module is wired into a live route -
 * it exists so that once an App is registered, the integration is a config/secrets change, not a new
 * engineering effort.
 *
 * Dependency-free by design (this package has no JWT/crypto library in its dependencies - see
 * package.json), using only the Web Crypto API (crypto.subtle), which is available identically in both
 * Node.js and the Cloudflare Workers runtime - no Node-only APIs, so this module runs unmodified in the
 * Worker.
 */

function base64UrlEncode(bytes: ArrayBuffer | Uint8Array): string {
  const arr = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
  let binary = "";
  for (const byte of arr) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function base64UrlEncodeString(value: string): string {
  return base64UrlEncode(new TextEncoder().encode(value));
}

function pemToDer(pem: string): ArrayBuffer {
  const base64 = pem.replace(/-----BEGIN [\s\S]*?-----/, "").replace(/-----END [\s\S]*?-----/, "").replace(/\s+/g, "");
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes.buffer;
}

// No explicit CryptoKey return-type annotation: that ambient type name comes from the DOM lib, which
// this project's tsconfig deliberately doesn't include (see the file-level doc comment on Node/Workers
// portability) - letting TS infer the type from crypto.subtle.importKey's own signature avoids needing it.
async function importRsaPrivateKey(pkcs8Pem: string) {
  return crypto.subtle.importKey("pkcs8", pemToDer(pkcs8Pem), { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" }, false, ["sign"]);
}

export interface SignAppJwtOptions {
  appId: string;
  /** PKCS#8 PEM private key, exactly as generated by GitHub's App settings page ("Generate a private
   * key" produces PKCS#1; convert with `openssl pkcs8 -topk8 -nocrypt` before storing as a secret - Web
   * Crypto's importKey only accepts PKCS#8, not PKCS#1). */
  privateKeyPkcs8Pem: string;
  /** Injectable for testing; defaults to the real clock. GitHub requires iat to not be in the future and
   * caps exp at 10 minutes from iat. */
  nowSeconds?: number;
}

/**
 * Signs a short-lived (9-minute, under GitHub's 10-minute cap) RS256 JWT authenticating as the App
 * itself - the first step of every App API call, used only to then exchange for a per-installation
 * access token (exchangeInstallationToken below). Never used directly against GitHub's regular REST
 * endpoints - only /app and /app/installations/*.
 */
export async function signAppJwt(options: SignAppJwtOptions): Promise<string> {
  const now = options.nowSeconds ?? Math.floor(Date.now() / 1000);
  const header = { alg: "RS256", typ: "JWT" };
  // iat set 60s in the past to tolerate clock drift between this process and GitHub's, per GitHub's own
  // documented recommendation for App JWTs.
  const payload = { iat: now - 60, exp: now + 9 * 60, iss: options.appId };
  const encodedHeader = base64UrlEncodeString(JSON.stringify(header));
  const encodedPayload = base64UrlEncodeString(JSON.stringify(payload));
  const signingInput = `${encodedHeader}.${encodedPayload}`;

  const key = await importRsaPrivateKey(options.privateKeyPkcs8Pem);
  const signature = await crypto.subtle.sign("RSASSA-PKCS1-v1_5", key, new TextEncoder().encode(signingInput));
  return `${signingInput}.${base64UrlEncode(signature)}`;
}

export interface InstallationToken {
  token: string;
  expiresAt: string;
}

/**
 * Exchanges an App JWT for a short-lived (1 hour, GitHub-controlled) installation access token scoped to
 * exactly the repositories/permissions the installation was granted - the token actually used for every
 * subsequent read (contents, actions, checks, pull-request metadata) against the installed repositories.
 * Least-privilege by construction: this token can never exceed what the installation itself was granted,
 * regardless of what the App's manifest requests.
 */
export async function exchangeInstallationToken(appJwt: string, installationId: string, fetchFn: typeof fetch = fetch): Promise<InstallationToken> {
  const res = await fetchFn(`https://api.github.com/app/installations/${installationId}/access_tokens`, {
    method: "POST",
    // User-Agent is REQUIRED - GitHub's API firewall 403s any request missing one ("Request forbidden
    // by administrative rules") with no other indication of what's wrong. The Workers fetch runtime,
    // unlike a browser or Node's http libs, does not add one automatically - found live 2026-08-21 when
    // the runner-dispatcher App's installation-token exchange failed 403 with this header absent.
    headers: {
      Authorization: `Bearer ${appJwt}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2026-03-10",
      "User-Agent": "DiffCI-App",
    },
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`installation token exchange failed (${res.status}): ${text.slice(0, 200)}`);
  }
  const body = (await res.json()) as { token: string; expires_at: string };
  return { token: body.token, expiresAt: body.expires_at };
}

async function hmacSha256Hex(secret: string, payload: string): Promise<string> {
  const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  const signature = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(payload));
  return Array.from(new Uint8Array(signature)).map((b) => b.toString(16).padStart(2, "0")).join("");
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

/**
 * Verifies a GitHub webhook delivery's X-Hub-Signature-256 header against the raw request body and the
 * App's configured webhook secret - the ONLY thing that distinguishes a real GitHub delivery from an
 * attacker-forged POST to the webhook endpoint. Must run against the raw, unparsed body (signing is
 * computed over exact bytes) - callers must read the body as text/bytes BEFORE JSON-parsing it, and pass
 * that same raw string here, never a re-serialized version.
 */
export async function verifyWebhookSignature(rawBody: string, signatureHeader: string | null, secret: string): Promise<boolean> {
  if (!signatureHeader || !signatureHeader.startsWith("sha256=")) return false;
  const expected = await hmacSha256Hex(secret, rawBody);
  return timingSafeEqual(signatureHeader.slice("sha256=".length), expected);
}
