-- GitHub OAuth support tables, same diffci-product D1 database, applied after schema.sql (references
-- users(id)). Kept as a second file rather than growing schema.sql, matching the rest of the codebase's
-- per-feature migration-file convention.
--
-- Apply with: wrangler d1 execute diffci-product --remote --file=src/auth/cloudflare/schema-oauth.sql

-- Provider identity linkage (Part 7). provider_user_id is GitHub's own immutable numeric user id
-- (never the username - GitHub usernames can be renamed; provider_login is kept purely as a
-- display/debugging convenience and is updated on every login, never used as a lookup key).
CREATE TABLE IF NOT EXISTS provider_identities (
  user_id TEXT NOT NULL REFERENCES users(id),
  provider TEXT NOT NULL CHECK (provider IN ('github')),
  provider_user_id TEXT NOT NULL,   -- GitHub's numeric id, as a string
  provider_login TEXT NOT NULL,     -- GitHub username at last login - display only, NEVER the identity key
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (provider, provider_user_id)
);
CREATE INDEX IF NOT EXISTS idx_provider_identities_user ON provider_identities(user_id);

-- Short-lived, single-use OAuth state (Part 6/11). A real table (not a stateless signed token) is
-- required specifically so a REPLAYED state can be detected and rejected (consumed_at set on first use)
-- - a purely stateless signed token could be replayed indefinitely within its validity window.
CREATE TABLE IF NOT EXISTS oauth_states (
  state TEXT PRIMARY KEY,           -- cryptographically random, generated by generateOAuthState()
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  consumed_at TEXT,
  redirect_to TEXT                  -- where to send the browser after a successful login, validated against an allowlist by the caller
);
